import Sidebar from "./components/Sidebar";
import DialogProvider from "./context/DialogContext";
import GlobalProvider from "./context/GlobalContext";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DialogProvider>
          <GlobalProvider>
          <div className="flex lg:flex-row md:flex-row sm:flex-row xs:flex-col xxs:flex-col w-full lg:h-screen md:h-screen sm:h-full xs:h-full xxs:h-full">
            <aside className="lg:w-72 md:w-72 sm:w-[40vw] xs:w-full xxs:w-full bg-[#1e213a] text-white lg:fixed md:fixed sm:fixed xs:relative xxs:relative z-20 ">
              {/* Aquí irá el contenido del sidebar */}
              <div className="flex left-0 absolute bg-MyClouds  mt-28 opacity-5 lg:w-72 lg:h-60 md:w-72 md:h-60 sm:w-72 sm:h-60 xs:w-[96vw] xs:h-[50vh] xxs:w-[95vw] xxs:h-[50vh] bg-no-repeat bg-cover  bg-center" />
              <div className="flex  absolute w-full justify-center lg:pt-40 md:pt-40 sm:pt-32 xs:pt-56 xxs:pt-56  ">
                <div className="flex  bg-SunAndCloud self-center bg-cover w-28 h-32  bg-no-repeat" />
              </div>
              <Sidebar />
            </aside>
            {/*bg-[#100e1d]*/}
            <main className="flex-1 z-10 lg:pl-52 md:pl-52 sm:pl-52 xs-px-10 ">
              {/* Aquí irá el contenido principal */}
              {children}
            </main>
          </div>
          </GlobalProvider>
        </DialogProvider>
      </body>
    </html>
  );
}

/*
        <main className="grid lg:grid-cols-5 md:grid-cols-4 sm:grid-cols-3  xs:grid-cols-2 xxs:grid-cols-1 w-full h-screen ">

*/
